Web/Models/User.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web.Models {
    public class UserConfig {
        [Display(Name = "Username")]
        public string UserName { get; set; }

        [Display(Name = "Password")]
        public string Password { get; set; }
    }

    [MetadataType(typeof(UserConfig))]
    [Table("users")]
    public class User {

        public User() {}

        [Column("id")]
        public int Id { get; set; }

        [Column("username")]
        [Required(ErrorMessage = "Username is required")]
        [StringLength(32, MinimumLength = 3, ErrorMessage = "Username must have min length of {2} and max Length of {1}")]
        public string UserName { get; set; }

        [Column("password")]
        [Required(ErrorMessage = "Password is required")]
        [StringLength(64, MinimumLength = 3, ErrorMessage = "Password must have min length of {2} and max Length of {1}")]
        public string Password { get; set; }

        public override string ToString() { return this.UserName; }
    }
}

Web/Controllers/SessionController.cs
using System;
using System.Web.Mvc;
using Web.Models;
using Web.DAO;
using Web.Filters;

namespace Web.Controllers {
    public class SessionController : Controller {
        private UserDAO dao;

        public SessionController() { this.dao = new UserDAO(); }

        public ActionResult Index() { return RedirectToAction("Login"); }

        public ActionResult Login() { return View(); }

        [HttpPost, ActionName("Login")]
        public ActionResult SignIn([Bind(Include = "UserName,Password")]User user) {
            User login = dao.Find(user.UserName, user.Password);
            if (login != null) {
                SessionController.SetSession(login, this);
                return RedirectToAction("Index", "Home");
            }
            return View(user);
        }

        [AuthFilter]
        public ActionResult Logout() {
            SessionController.SetSession(null, this);
            return RedirectToAction("Login");
        }

        private User GetUser(int? id) {
            if (id == null) return null;
            return this.dao.FindById((int)id);
        }

        /* statics codes */
        public static readonly string[] keys = { "user_username", "user_id" };

        public static bool Mine(int? id, Controller controller) {
            if (id == null || controller.Session[SessionController.keys[1]] == null) return false;
            return (int)controller.Session[SessionController.keys[1]] == id;
        }
        public static void SetSession(User user, Controller controller) {
            if (user != null) {
                controller.Session[SessionController.keys[0]] = user.UserName;
                controller.Session[SessionController.keys[1]] = user.Id;
                return;
            }
            controller.Session.Remove(SessionController.keys[0]);
            controller.Session.Remove(SessionController.keys[1]);
        }
        public static int? GetSessionUserID(Controller controller) {
            return (int?)controller.Session[SessionController.keys[1]];
        }
    }
}

Web/Controllers/UserController.cs
using System;
using System.Web.Mvc;
using Web.Models;
using Web.DAO;
using Web.Filters;

namespace Web.Controllers {
    public class UserController : Controller {
        private UserDAO dao;

        public UserController() { this.dao = new UserDAO(); }

        public ActionResult Index() { return RedirectToAction("Account/" + (Session[SessionController.keys[0]])); }

        public ActionResult New() { return View(); }

        [HttpPost, ActionName("New")]
        public ActionResult Create([Bind(Include = "UserName,Password")]User user) {
            if (ModelState.IsValid && dao.Add(user)) {
                SessionController.SetSession(user, this);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("UserName", "Please, choose other username");
            return View();
        }

        [AuthFilter]
        public ActionResult Account(string username) {
            User user = this.dao.FindByUserName(username);
            if (user == null || !SessionController.Mine(user.Id, this)) { return RedirectToAction("Index"); }
            return View(user);
        }

        [AuthFilter, HttpPost, ActionName("Account")]
        public ActionResult Update([Bind(Include = "Id,UserName,Password")]User user) {
            if (user == null) return RedirectToAction("Index");
            if (ModelState.IsValid && SessionController.Mine(user.Id, this)) {
                SessionController.SetSession(user, this);
                dao.Update(user);
                ViewBag.Updated = true;
            }
            return View(user);
        }

        [AuthFilter]
        public ActionResult Delete(int? id) { return RedirectToAction("Index"); }

        [AuthFilter, HttpDelete]
        public ActionResult Delete(int id, FormCollection collection) {
            if (SessionController.Mine(id, this)) {
                this.dao.Delete(id);
                SessionController.SetSession(null, this);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Account");
        }
    }
}

Web/Views/User/Account.cshtml
@using Web.Models
@model User

@{
    ViewBag.Title = "User Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@ViewBag.Title</h4>
<div class="col-md-6 table-responsive table-dark">
    <table class="table table-hover table-striped table-sm">
        <tr>
            <th>Fields</th>
            <th>Values</th>
        </tr>
        @using (Html.BeginForm()) {
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <tr>
                <td>@Html.DisplayNameFor(model => model.Id)</td>
                <td>
                    @Html.DisplayFor(model => model.Id)
                    @Html.HiddenFor(model => model.Id)
                    @Html.ValidationMessageFor(model => model.Id) 
                </td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.UserName)</td>
                <td>
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @style="background-color: gray", @readonly = "readonly" }}) 
                    @Html.ValidationMessageFor(model => model.UserName) 
                </td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Password)</td>
                <td>
                    @Html.PasswordFor(model => model.Password, new {@class="form-control", placeholder="Password", autofocus = true })
                    @Html.ValidationMessageFor(model => model.Password) 
                </td>
            </tr>
            <tr> 
                <td colspan="2" align="left">
                    <button type="submit" class="btn btn-sm btn-primary" value="Save"><i data-feather="save"></i> Save</button>
                </td>
            </tr>
        }
        @using (Html.BeginForm("Delete", "User", new { Id = @Model.Id })) {
            @Html.HttpMethodOverride(HttpVerbs.Delete)

            <input type='hidden' id='hiddenPage' name='hiddenPage' value='new'/>
            <button type="submit" value="Delete" class="btn btn-sm btn-danger" onclick="return confirm('Delete @Model.Id @Model.UserName');"><i data-feather="trash-2"></i></button>
        }
    </table>
</div>

@if(ViewBag.Updated==true) {
    <div class="alert alert-success" >             
        <strong>Thank you!</strong> Your query has been submitted. 
    </div>
}
<script>
    function setActiveTab() {
        $("#li_user").addClass("active");
    }
</script>

Web/Views/User/New.cshtml
@model Web.Models.User

@{
    ViewBag.Title = "New User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@ViewBag.Title</h4>

@using (Html.BeginForm()) {
  <div class="row">
    <div class="col-md-6 table-responsive">
        <table class="table table-hover table-striped table-sm">
            <thead class="table-secondary">
                <tr>
                    <th>Fields</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.UserName)</td>
                    <td>
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { autofocus = true }}) 
                        @Html.ValidationMessageFor(model => model.UserName) 
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Password)</td>
                    <td>
                        @Html.PasswordFor(model => model.Password, new {@class="form-control", placeholder="Password"}) 
                        @Html.ValidationMessageFor(model => model.Password) 
                    </td>
                </tr>
            </tbody>
        </table>
        <button type="submit" class="btn btn-sm btn-primary" value="Create User"><i data-feather="save"></i> Create User</button>
        <span> <a href="@Url.Action("Login", "Session")">&nbsp<b> Go Back </b></a></span>
    </div>
  </div>
}

<script>
    function setActiveTab() {
        $("#li_users").addClass("active");
    }
</script>