Web/Models/Job.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web.Models {
    public class JobConfig {
        [Display(Name = "Job Name")]
        public string JobName { get; set; }

        [Display(Name = "Birthday")]
        public DateTime? Birth { get; set; }

        [Display(Name = "User")]
        public int UserId { get; set; }
    }

    [MetadataType(typeof(JobConfig))]
    [Table("jobs")]
    public class Job {
        public Job() { this.Birth = DateTime.Now; }

        [Column("id")]
        public int Id { get; set; }

        [Column("job_name")]
        [Required(ErrorMessage = "Job name is required")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "JobName must have min length of {2} and max Length of {1}")]
        public string JobName { get; set; }

        [Column("birth")]
        public DateTime? Birth { get; set; }

        [Column("user_id")]
        public int UserId { get; set; }
        public virtual User User { get; set; }

        public override string ToString() {
            return "["+Id+":"+JobName+":"+UserId+"]";
        }
    }
}

Web/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.DAO;
using System.Data.Entity;
using PagedList;
using Web.Filters;

namespace Web.Controllers {
    [AuthFilter]
    public class JobController : Controller {
        private readonly UserDAO dao_users;
        private readonly JobDAO dao_jobs;
        private readonly int numRows = 7;

        public JobController() { this.dao_jobs = new JobDAO(); this.dao_users = new UserDAO(); }

        public ActionResult Index(int? page) {
            List<Job> jobs = (List<Job>)this.dao_jobs.List(); 
            List<Job> sortedJobs = jobs.OrderBy(p => p.Birth).ToList();

            int iPage = page ?? 1;
            return View("Index", sortedJobs.ToPagedList(iPage, numRows));
        }

        public ActionResult Show(int? id) { 
            Job job = this.GetJob(id);
            if (job == null) { return RedirectToAction("Index"); }
            return View(job);
        }

        public ActionResult New() { 
            Job job = new Job { UserId = (int) Session[SessionController.keys[1]] };
            ViewBag.UsersNames = UsersOrderByUserName;
            return View(job); 
        }

        [HttpPost, ActionName("New")]
        public ActionResult Create([Bind(Include = "JobName, UserId")]Job job) {
            job.Birth = DateTime.Now;
            if (ModelState.IsValid && dao_jobs.Add(job)) return RedirectToAction("Index");

            ViewBag.UsersNames = UsersOrderByUserName;
            return View(job);
        }

        public ActionResult Edit(int? id) {
            Job job = this.GetJob(id);
            if (job == null || !SessionController.Mine(job.UserId, this)) { return RedirectToAction("Index"); } 
            return View(job); 
        }

        [HttpPost, ActionName("Edit")]
        public ActionResult Update([Bind(Include = "Id,UserId,JobName,Birth")]Job job) {
            if (job != null || SessionController.Mine(job.UserId, this))
                if (ModelState.IsValid && dao_jobs.Update(job))
                    return RedirectToAction("Index");
            return View(job);
        }

        public ActionResult Delete(int? id) { return RedirectToAction("Index"); }

        [HttpDelete]
        public ActionResult Delete(int id, FormCollection collection) {
            Job job = this.dao_jobs.FindById(id);
            if (SessionController.Mine(job.UserId, this) && this.dao_jobs.Delete(id))
                return RedirectToAction("Index", new { page = collection["hiddenPage"] });

            return RedirectToAction("Index", "Home");
        }

        private Job GetJob(int? id) { if (id == null) return null; return this.dao_jobs.FindById((int)id); }
        private SelectList UsersOrderByUserName { get { return new SelectList(this.dao_jobs.Users(true), "Id", "UserName"); } }
    }
}

/* 
 * SelfList(SessionConfig.GetSessionUserID(this));
 * User user = this.dao_users.FindByUserName((string) Session[SessionConfig.keys[0]]);
 * try { job.Birth = DateTime.Parse(Request.Form["Birth"]); } catch { ModelState.AddModelError("Birth", "Date format error!!!"); } 
 */

Web/Views/Job/Edit.cshtml
@model Web.Models.Job

@{
    ViewBag.Title = "Job " + @Model.Id;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@ViewBag.Title</h4>

@using (Html.BeginForm()) {
  <div class="row">
    <div class="col-md-6 table-responsive">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <table class="table table-hover table-striped table-sm">
            <thead class="table_head">
                <tr>
                    <th>Fields</th>
                    <th>Values</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Id)</td>
                    <td>
                        @Html.DisplayFor(model => model.Id)
                        @Html.ValidationMessageFor(model => model.Id) 
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.UserId)</td>
                    <td>
                        @Html.DisplayFor(model => model.UserId) 
                        @Html.HiddenFor(model => model.UserId) 
                        @Html.ValidationMessageFor(model => model.UserId) 
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.JobName)</td>
                    <td>
                        @Html.EditorFor(model => model.JobName) 
                        @Html.ValidationMessageFor(model => model.JobName) 
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Birth)</td>
                    <td>
                        @Html.DisplayFor(model => model.Birth) 
                        @Html.HiddenFor(model => model.Birth) 
                        @Html.ValidationMessageFor(model => model.Birth) 
                    </td>
                </tr>
                <!-- @*
                <tr>
                    <td>@Html.LabelFor(model => model.UserId)</td>
                    <td>
                        @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control", @style="background-color: gray", @readonly = "readonly" }}) 
                        @Html.ValidationMessageFor(model => model.UserId) 
                    </td>
                </tr>
                
                <tr>
                    <td>@Html.LabelFor(model => model.UserId, "User")</td>
                    <td>
                        @Html.DropDownListFor(model => model.UserId, new SelectList(ViewBag.UsersNames, "Value", "Text")) 
                        @Html.ValidationMessageFor(model => model.UserId) 
                    </td>
                </tr>
                
                *@ -->
            </tbody>
        </table>
        @if(@Session["user_id"].Equals(@Model.UserId)) {
            <button type="submit" class="btn btn-sm btn-primary" value="Save"><i data-feather="save"></i> Save</button>
        }
    </div>
  </div>
}

<script>
    function setActiveTab() {
        $("#li_job").addClass("active");
        //$('#Birth').datepicker({ dateFormat: 'dd/mm/yy' }).val();
    }
</script>


Web/Views/Job/Index.cshtml
@using Web.Models;
@using PagedList;
@using PagedList.Mvc;
@model IPagedList < Job >

@{ ViewBag.Title = "Jobs Queue";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@ViewBag.Title</h4>

<div class="table-responsive">
	<table class="table table-hover table-striped table-sm">
		<thead class="table_head">
			<tr>
                <td>@Html.DisplayNameFor(model => model.First().Id)</td>
				<td>@Html.DisplayNameFor(model => model.First().JobName)</td>
				<td>@Html.DisplayNameFor(model => model.First().User.UserName)</td>
				<td>@Html.DisplayNameFor(model => model.First().Birth)</td>
				<td>Details</td>
				<td>Edit</td>
				<td>Delete</td>
			</tr>
		</thead>
		<tbody>
    		@foreach(Job p in @Model) { 
    			<tr>
                    <td>@p.Id</td>
    				<td>@p.JobName</td>
    				<td>@p.User.UserName</td>
    				<td>@p.Birth</td>
    				<td>
                        <a href="@Url.Action("Show", "Job", new { Id = p.Id })"> <button class="btn btn-sm btn-info"><i data-feather="list"></i></button> </a>
    				</td>
    				<td>
                        @if(@Session["user_id"].Equals(@p.UserId)) {
                            <a href="@Url.Action("Edit", "Job", new { Id = p.Id })" >
                                <button class="btn btn-sm btn-success"><i data-feather="edit"></i></button>
                            </a>
                        } else { <button class="btn btn-sm btn-secondary" disabled="true"><i data-feather="edit"></i></button> }
                    </td>
    				<td>
    				@using (Html.BeginForm("Delete", "Job", new { Id = p.Id })) {
                        @Html.HttpMethodOverride(HttpVerbs.Delete)

    					<input type='hidden' id='hiddenPage' name='hiddenPage' value='@Request.QueryString["page"]'/>
                        if(@Session["user_id"].Equals(@p.UserId)) {
                            <button type="submit" value="del" class="btn btn-sm btn-danger" onclick="return confirm('Delete @p.JobName @p.UserId');"><i data-feather="trash-2"></i></button>                    
                        } else {<button value="del" class="btn btn-sm btn-secondary" disabled="true"><i data-feather="trash-2"></i></button>}
                    }
    				</td>
    			</tr>
    		}
		</tbody>
	</table>
	@Html.PagedListPager( Model , page => Url.Action("Index", new { page }))
	@* @Html.ActionLink("Create New", "New", "Job", null, new { @class = "btn btn-sm btn-success"}) *@    
    <a href="@Url.Action("New", "Job")"> <button class="btn btn-sm btn-success"><i data-feather="plus"></i> Create New</button> </a>
    
</div>

<script>
    function setActiveTab() {
    	$("#li_job").addClass("active");
    }
</script>

Web/Views/Job/New.cshtml
@model Web.Models.Job

@{
    ViewBag.Title = "Create a Job";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@ViewBag.Title</h4>
<div class="row col-md-6 table-responsive">
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <table class="table table-hover table-striped table-sm">
            <thead class="table_head">
                <tr>
                    <th>Fields</th>
                    <th>Values</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.JobName)</td>
                    <td>
                        @Html.EditorFor(model => model.JobName) 
                        @Html.ValidationMessageFor(model => model.JobName) 
                    </td>
                </tr>
                
                <tr>
                    <td>@Html.LabelFor(model => model.UserId, "Owner User")</td>
                    <td>
                        @Html.DropDownListFor(model => model.UserId, new SelectList(ViewBag.UsersNames, "Value", "Text")) 
                        @Html.ValidationMessageFor(model => model.UserId) 
                    </td>
                </tr>
                
                <!-- @*
                <tr>
                    <td>@Html.LabelFor(model => model.Birth, "Birthday about")</td>
                    <td>
                        @Html.DisplayFor(model => model.Birth) 
                        @Html.HiddenFor(model => model.Birth)
                        @Html.ValidationMessageFor(model => model.Birth) 
                    </td>
                </tr> 
            
                <tr>
                    <td>@Html.DisplayNameFor(model => model.UserName)</td>
                    <td>
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @style="background-color: gray", @Value = Session["user_username"], @readonly = "readonly" }}) 
                        @Html.ValidationMessageFor(model => model.UserName) 
                    </td>
                </tr>
                *@ -->
            </tbody>
        </table>
        <button type="submit" class="btn btn-sm btn-primary" value="Save"><i data-feather="save"></i> Save</button>
    }
</div>


<script>
    function setActiveTab() {
    	$("#li_job").addClass("active");
    }
</script>

Web/Views/Job/Show.cshtml
@using Web.Models
@model Job


@{
    ViewBag.Title = "Job Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@ViewBag.Title</h4>
<div class="row">
    <div class="col-md-6 table-responsive">
        <table class="table table-hover table-striped table-sm">
            <thead class="table_head">
                <tr>
                    <th>Fields</th>
                    <th>Values</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Id)</td>
                    <td>@Html.DisplayFor(model => model.Id)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.JobName)</td>
                    <td>@Html.DisplayFor(model => model.JobName)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.UserId)</td>
                    <td>@Html.DisplayFor(model => model.UserId)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Birth)</td>
                    <td>@Html.DisplayFor(model => model.Birth)</td>
                </tr>
            </tbody>

        </table>
        <a href="@Url.Action("Index", "Job")" > <button class="btn btn-sm btn-info" ><i data-feather="chevrons-left"></i></button> </a>
        @* @Html.ActionLink("Back", "Index", "Job", null, new { @class = "btn btn-primary"}) *@
    </div>
</div>

<script>
    function setActiveTab() {
    	$("#li_job").addClass("active");
    }
</script>